[package]
name = "monadlisa"
version = "0.1.1"
authors = ["suiGn <admin@neurons.me>"]
edition = "2021"
description = "MonadLisa"
license = "MIT OR Apache-2.0"
repository = "https://github.com/neurons-me/this.audio"
homepage = "https://neurons.me"
readme = "README.md"
keywords = ["GUI", "Data"]
categories = ["command-line-utilities", "encoding"]
[dependencies]
